### ISSUE TITLE
AskYN breaking to terminal animation!

### ISSUE THREAD

**Issue by EmeraldMike** [SkylixGH/NitroJS#4]
So when you put a `terminal.animate()` before a `terminal.askYN()` for some reason this doesn't allow the askYN to happen and when you hit enter or try to input something it just continues the animation. here is my code for referance.
```
import terminal, { State } from "@skylixgh/nitrojs-terminal";

terminal.animate("wating user input")

terminal.askYN("Want a meow?", true, (ans) => {
if (ans){
    terminal.stopAnimation(State.success, "Meow Meow Meow Meow")
}else{
    terminal.stopAnimation(State.error, "Meow did not happen );")
}
})
```
the code without the terminal.animate works fine!

**Comment by EmeraldMike** [comment]
Here is one that does something close without animate.
```
import terminal, { State } from "@skylixgh/nitrojs-terminal";

terminal.notice("wating user input")

terminal.askYN("Want a meow?", true, (ans) => {
if (ans){
    terminal.success("Meow Meow Meow Meow")
}else{
    terminal.error("Meow did not happen );")
}
})
```

**Comment by XFaonAE** [comment]
colcollcolcollicolcollcolcolliscolcollcolcollicolcollcolcollision lcollcolcollicolcollcolcolliscolcollcolcollicolcollcolcollisi

**Comment by MelonFruit7** [comment]
Fixed in v2
