### ISSUE TITLE
Can't colorize terminal animate

### ISSUE THREAD

**Issue by EmeraldMike** [SkylixGH/NitroJS#7]
you can color text but you can not colorize the animate.

**Comment by XFaonAE** [comment]
Please provide a code example

**Comment by EmeraldMike** [comment]
So the terminal.animate takes 1 pram that is the text. terminal does allow you to color the text like this
```
terminal.animate(terminal.hexColorize("Meow meow","#4287f5"))
```
but terminal.animate has 0 peram to make something like a green spinner or red spinner

**Comment by MelonFruit7** [comment]
Fixed in v2
